### PR TITLE
Update camel documentation page with Fedora theme

### PR DESCRIPTION
**Pull request by acoburn**
Partially resolves: https://jira.duraspace.org/browse/FCREPO-1972

### CODE REVIEW

**Comment by whikloj** [comment]
I have no idea if I can test this, or is it more a case of "if you know how it works, you'll know if it works"?

'Cause I don't know how it works, but it looks simple enough of a change.

**Comment by acoburn** [comment]
@whikloj you can test this by checking out this branch and viewing the `index.html` page in a browser.

**Comment by acoburn** [comment]
The idea is to make this page: http://fcrepo4-exts.github.io/fcrepo-camel/ look more like this page: http://docs.fcrepo.org/

**Comment by whikloj** [comment]
And it does. Nice work.

**Pull request merged**
