### PR TITLE
Update Jena to 3.x

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-2280

### CODE REVIEW

**Comment by birkland** [comment]
Excellent - don't have an opportunity to test at the moment, but will see if this and #128 fix the issues we've been seeing running fcrepo-camel alongside code that uses fcrepo-java-client 0.2.x and Jena 3.x in the same Karaf container.

**Comment by acoburn** [comment]
@birkland and I'm working on an update to use the 0.2.x version of fcrepo-java-client. Once that's complete, I'll cut a 4.5.0 release

**Comment by birkland** [comment]
@acoburn Wonderful!.  I took a quick look at that a few days ago to see if doing so was low-hanging fruit, but backed out when it looked like it would be necessary to interpret Prefer headers, and translate them into method calls on the client (or something along those lines)

**Comment by acoburn** [comment]
Yes, that's exactly what's taking so long -- the Prefer header logic

**Pull request merged**
