### PR TITLE
Update Content-Type header to include the utf8 charset

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-1991

### CODE REVIEW

**Comment by whikloj** [comment]
@acoburn, This seems like a logical simple change to me, but do you want me to run this with some wide Unicode characters just to make sure?

**Comment by acoburn** [comment]
@whikloj I've tested locally and it works, but yes, please feel free to test. I found that including unicode characters in a PATCH to Fedora via sparql-update mangles the characters (I must be doing something wrong), but using PUT or POST with the UTF-8 chars in a file works great.

Here's what I did to test this in Karaf: you can start with the standard `feature:install fcrepo-indexing-triplestore`, which installs the old version of camel. Then, if you drop the newly build `fcrepo-camel` bundle in `$KARAF_HOME/deploy` and then issue `feature:stop fcrepo-camel`, that should stop version 4.4.1 but allow 4.4.2-SNAPSHOT to keep running. The `fcrepo-camel-toolbox` routes will then pick up the newer `fcrepo-camel` bundle.

I tested this with Fuseki, and the unicode characters made it through just fine. I think it would be good to have a follow-on ticket in fcrepo-camel-toolbox with an appropriate integration test, but that has to wait until we have a new release of fcrepo-camel.

**Comment by ajs6f** [comment]
"I found that including unicode characters in a PATCH to Fedora via sparql-update mangles the characters "

That's troubling. That shouldn't be the case, via the HTTP API. Can you give an example? It sounds like a bug…

**Comment by acoburn** [comment]
@ajs6f I agree. Here's an example. Put this in a file (or use the HTML UI):

    PREFIX dc: <http://purl.org/dc/elements/1.1/> 
    INSERT {
        <> dc:title "Die von Blumenbach gegründete anthropologische Sammlung der Universität" .
    } WHERE {}

And then issue this:

    curl -i -XPATCH localhost:8080/fcrepo/rest/dev/ -H"Content-Type: application/sparql-update; charset=utf-8" --data-binary @patch.txt

or:

    curl -i -XPATCH localhost:8080/fcrepo/rest/dev/ -H"Content-Type: application/sparql-update" --data-binary @patch.txt

The presence or absence of `charset=utf-8` seems to make no difference.

**Comment by acoburn** [comment]
@ajs6f: just a note -- the `application/sparql-update` content type is supposed to *always* be utf-8: https://www.w3.org/TR/sparql11-update/#mediaType

So there should be no need to add `charset=utf-8` to the content-type header, meaning it is the task of Fedora to assume that the input is always utf-8.

**Comment by acoburn** [comment]
@ajs6f there is no encoding listed here: https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-http-api/src/main/java/org/fcrepo/http/api/FedoraLdp.java#L423

Meaning it defaults to "the default encoding of the platform". I suspect that that's the culprit.

**Comment by acoburn** [comment]
Tracking the PATCH encoding issue here: https://jira.duraspace.org/browse/FCREPO-1993

**Comment by sprater** [comment]
This is likely related to the platform encoding bug I found while testing on Windows:

https://jira.duraspace.org/browse/FCREPO-1979

**Comment by whikloj** [comment]
@acoburn So I tried the patch above and (perhaps I misunderstood the issue) but it seems to work fine for me. Should it not appear in Fedora or Fuseki appropriately even **with** this PR?

**Comment by ajs6f** [comment]
This is a common but bad habit to which I plead as guilty as anyone. The platform default encoding is almost never the right choice. @barmintor used to program Java on mainframes, and I imagine there were some truly weird encodings available there. Java 8 got rid of a lot of the boilerplate `try {} catch (UnsupportedEncodingException e) {/* impossible */}` this used to cause, so we've got less and less excuse.

**Comment by whikloj** [comment]
I'm sorry I didn't even think that my use of an Ubuntu vagrant means that my default encoding scheme is probably UTF-8 anyways.
Otherwise this PR tests appropriately for PUT and POST with UTF-8 characters. 

:+1:  Merging

**Comment by barmintor** [comment]
in defense of mainframes, there was just the [one weird encoding](https://en.wikipedia.org/wiki/EBCDIC) (though byte order was also fun).

**Pull request merged**
