### PR TITLE
Add support for component-wide configuration of baseUrl

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-2018

### CODE REVIEW

**Comment by awoods** [comment]
Does this update mean that configuration like the following would become optional?
https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/blob/master/fcrepo-serialization/src/main/cfg/org.fcrepo.camel.serialization.cfg#L10

If so, where would the centralized configuration be set? ..and would the above mentioned configuration element override a centralized config?

**Comment by acoburn** [comment]
@awoods: yes, that value would go away and all configuration for the `fcrepo` component could be centralized, sort of like what I'm doing with the activemq component in this PR: https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/pull/89

**Comment by acoburn** [comment]
... and to continue: for the fcrepo-camel-toolbox, we can _either_ have a centralized configuration or a component-by-component configuration. This PR, simply makes both options possible. Right now, you must set the Fedora URL on each and every camel endpoint.

**Comment by awoods** [comment]
Should there be an example blueprint.xml or cfg file associated with this PR?

**Comment by acoburn** [comment]
@awoods do you mean for integration testing? or as documentation?

**Comment by acoburn** [comment]
I don't see any need to provide a cfg file, since that is very specific to a karaf-based deployment and the use of a certain type of property placeholder. The only use of a blueprint.xml file would be for integration testing, but we're already doing that. So there, too, I don't see how it would add anything to the integration test we already have.

As for documentation, yes, it certainly should be documented in the README, which it currently is not.

**Comment by acoburn** [comment]
Documentation added.

**Pull request merged**
